plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0

relative_links:
  enabled: true
  collections: true

exclude:
  - README.md

markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter: rogue
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  input: GFM

highlighter: rogue
