plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

exclude:
  - README.md

markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter: rogue
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  input: GFM

highlighter: rogue

default:
  portfolio_image: assets/profile.jpg
  portfolio_alt: Me at my birthday party in China.

portfolio:
  name: Tiger Yu
  description: A CS student at UCSB
  text: I am a UCSB student majoring in computer science. I work on some CS projects during my free time.
  socials:
    - type: email
      account: tigeryu8900@gmail.com
    - type: github
      account: tigeryu8900
    - type: reddit
      account: randomweeb-69420
    - type: discord
      account: 617560890752892928
    - icon: fa-brands fa-weixin
      attrib: |
        data-bs-container="body"
        data-bs-toggle="popover"
        data-bs-placement="top"
        data-bs-html="true"
        data-bs-content="<img class=&quot;container&quot; src=&quot;/assets/wechat-qr.jpg&quot;/>"
