plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0

relative_links:
  enabled: true
  collections: true

exclude:
  - README.md

markdown: kramdown

kramdown:
  parse_block_html: true
